[project]
name = "curso-fastapi-pro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.118.0",
    "jinja2>=3.1.6",
    "pycopg>=0.3.0",
    "python-dotenv>=1.2.1",
    "python-jose>=3.5.0",
    "python-multipart>=0.0.22",
    "sqlmodel>=0.0.34",
    "supabase>=2.28.0",
    "uvicorn>=0.37.0",
]
